---
# Java Ekart Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekartapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekartapp
  template:
    metadata:
      labels:
        app: ekartapp
    spec:
      containers:
      - name: ekartapp
        image: kcmchandramoulli/kcmekart:latest  #image from docker hub
        ports:
        - containerPort: 8070
        # env:
        # - name: SPRING_DATASOURCE_URL
        #   value: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        # - name: SPRING_DATASOURCE_USERNAME
        #   value: root
        # - name: SPRING_DATASOURCE_PASSWORD
        #   value: Test@123
---
# Bank Application Service
apiVersion: v1
kind: Service
metadata:
  name: ekartapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8070
  selector:
    app: ekartapp