name: CI

on:
  push:
    branches:
      - "master"
      - "task/**"
  pull_request:
    branches:
      - "master"
      - "task/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  maven-compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Check Versions
        run: |
          java --version  
          mvn --version

      - name: Maven package
        run: |
          mvn clean package -DskipTests=true

      - name: ls -la
        run: |
          ls -la
          ls -la target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Build Docker Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: docker_file
      #     push: true
      #     tags: kcmchandramoulli/kcmekart:latest

      - name: docker build&push
        run: |
          docker build -t kcmchandramoulli/kcmekart:latest .
          docker push kcmchandramoulli/kcmekart:latest
